services:
  - type: web
    name: drawspace-http-backend
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm --filter=http-backend build
    startCommand: cd apps/http-backend && node dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: drawspace-ws-backend
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm --filter=ws-backend build
    startCommand: cd apps/ws-backend && node dist/index.js
    envVars:
      - key: WS_PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info